name: Release prometheus-configurator

on:
  schedule:
    - cron: "0 4 * * 3"
  workflow_dispatch:

concurrency: release

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  prerelease:
    name: Create prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - uses: newrelic/release-toolkit/generate-changelog@v1
        with:
          excluded-dirs: charts
      - uses: newrelic/release-toolkit/is-held@v1
      - uses: newrelic/release-toolkit/link-changelog@v1
        with:
          dictionary: .github/dictionary.yaml
      - uses: newrelic/release-toolkit/next-version@v1
        id: version
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: newrelic/release-toolkit/update-changelog@v1
        with:
          version: ${{ steps.version.outputs.next-version }}
      - name: Commit updated changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog with changes from ${{ steps.version.outputs.next-version }}"
          git push -u origin main
      - uses: newrelic/release-toolkit/render@v1
      - name: Create Prerelease
        run: |
          gh release create ${{ steps.version.outputs.next-version }} --prerelease --target $GITHUB_SHA --notes-file CHANGELOG.partial.md
      - name: Dispatch releaseImages workflow for prerelease
        run: |
          gh workflow run releaseImages.yaml -f releaseType=prerelease -f version=${{ steps.version.outputs.next-version }}
